from __future__ import annotations

from miser.models import SavingsReceipt


def render_route_config(receipts: list[SavingsReceipt]) -> str:
    lines = [
        "# Generated by Miser. Review, replay-test, then deploy.",
        "routes:",
    ]

    for receipt in receipts:
        primary, fallback = _split_recommended_route(receipt.recommended_route)
        lines.extend(
            [
                f"  - workflow: {receipt.workflow}",
                f"    cluster_id: {receipt.cluster_id}",
                f"    current_route: {receipt.current_route}",
                f"    primary: {primary}",
                f"    fallback: {fallback}",
                f"    quality_guard: \"{receipt.quality_guard}\"",
                "    rollback: enabled",
                "    approval_required: true",
                f"    estimated_monthly_savings_usd: {receipt.estimated_savings:.2f}",
            ]
        )

    return "\n".join(lines) + "\n"


def _split_recommended_route(route: str) -> tuple[str, str]:
    if "->" not in route:
        return route.strip(), "frontier_fallback"

    primary, fallback = route.split("->", 1)
    return primary.strip(), fallback.strip()
