package miser

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

type AnalyzerConfig struct {
	MinClusterSize       int
	MinMonthlySavingsUSD float64
	MinQualityScore      float64
}

func Analyze(calls []LLMCall, config AnalyzerConfig) []SavingsReceipt {
	if config.MinClusterSize == 0 {
		config.MinClusterSize = 3
	}
	if config.MinMonthlySavingsUSD == 0 {
		config.MinMonthlySavingsUSD = 1
	}
	if config.MinQualityScore == 0 {
		config.MinQualityScore = 0.95
	}

	var receipts []SavingsReceipt
	for clusterID, group := range groups(calls) {
		if len(group) < config.MinClusterSize {
			continue
		}
		receipt := buildReceipt(clusterID, group, config)
		if receipt.EstimatedSavings >= config.MinMonthlySavingsUSD {
			receipts = append(receipts, receipt)
		}
	}
	sort.Slice(receipts, func(i, j int) bool {
		return receipts[i].EstimatedSavings > receipts[j].EstimatedSavings
	})
	return receipts
}

func RenderReceipts(receipts []SavingsReceipt) string {
	if len(receipts) == 0 {
		return "Miser found no savings candidates.\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "Miser found %d savings candidate%s\n", len(receipts), plural(len(receipts)))
	for _, receipt := range receipts {
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, receipt.Workflow)
		fmt.Fprintf(&b, "Cluster: %s\n", receipt.ClusterID)
		fmt.Fprintf(&b, "Current route: %s\n", receipt.CurrentRoute)
		fmt.Fprintf(&b, "Monthly calls: %d\n", receipt.MonthlyCalls)
		fmt.Fprintf(&b, "Current monthly cost: $%.2f\n", receipt.CurrentMonthlyCost)
		fmt.Fprintf(&b, "Estimated monthly cost: $%.2f\n", receipt.EstimatedMonthlyCost)
		fmt.Fprintf(&b, "Estimated savings: $%.2f (%.0f%%)\n", receipt.EstimatedSavings, receipt.SavingsRate*100)
		fmt.Fprintf(&b, "Recommended route: %s\n", receipt.RecommendedRoute)
		fmt.Fprintf(&b, "Quality guard: %s\n", receipt.QualityGuard)
		fmt.Fprintf(&b, "Rollback: %s\n", receipt.Rollback)
		fmt.Fprintf(&b, "Why: %s\n", receipt.Reason)
	}
	return b.String()
}

func RenderRoutes(receipts []SavingsReceipt) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by Miser. Review, replay-test, then deploy.")
	fmt.Fprintln(&b, "routes:")
	for _, receipt := range receipts {
		primary, fallback := splitRoute(receipt.RecommendedRoute)
		fmt.Fprintf(&b, "  - workflow: %s\n", receipt.Workflow)
		fmt.Fprintf(&b, "    cluster_id: %s\n", receipt.ClusterID)
		fmt.Fprintf(&b, "    current_route: %s\n", receipt.CurrentRoute)
		fmt.Fprintf(&b, "    primary: %s\n", primary)
		fmt.Fprintf(&b, "    fallback: %s\n", fallback)
		fmt.Fprintf(&b, "    quality_guard: %q\n", receipt.QualityGuard)
		fmt.Fprintln(&b, "    rollback: enabled")
		fmt.Fprintln(&b, "    approval_required: true")
		fmt.Fprintf(&b, "    estimated_monthly_savings_usd: %.2f\n", receipt.EstimatedSavings)
	}
	return b.String()
}

func buildReceipt(clusterID string, calls []LLMCall, config AnalyzerConfig) SavingsReceipt {
	sort.Slice(calls, func(i, j int) bool { return calls[i].Timestamp.Before(calls[j].Timestamp) })
	observedCost := 0.0
	totalTokens := 0
	var samples []string
	for _, call := range calls {
		observedCost += call.CostUSD
		totalTokens += call.TotalTokens()
		samples = appendSample(samples, call.ID)
	}

	multiplier := monthlyMultiplier(calls)
	currentMonthlyCost := observedCost * multiplier
	recommendedRoute, costFactor, reason := recommendRoute(calls, float64(totalTokens)/float64(len(calls)))
	estimatedMonthlyCost := currentMonthlyCost * costFactor
	estimatedSavings := currentMonthlyCost - estimatedMonthlyCost
	if estimatedSavings < 0 {
		estimatedSavings = 0
	}
	savingsRate := 0.0
	if currentMonthlyCost > 0 {
		savingsRate = estimatedSavings / currentMonthlyCost
	}

	return SavingsReceipt{
		ClusterID:            clusterID,
		Workflow:             calls[0].Workflow,
		CurrentRoute:         calls[0].Route(),
		MonthlyCalls:         int(float64(len(calls)) * multiplier),
		CurrentMonthlyCost:   currentMonthlyCost,
		EstimatedMonthlyCost: estimatedMonthlyCost,
		EstimatedSavings:     estimatedSavings,
		SavingsRate:          savingsRate,
		RecommendedRoute:     recommendedRoute,
		QualityGuard:         fmt.Sprintf("replay_eval >= %.2f", config.MinQualityScore),
		Rollback:             "enabled",
		Reason:               reason,
		SampleCallIDs:        samples,
	}
}

func monthlyMultiplier(calls []LLMCall) float64 {
	if len(calls) < 2 {
		return 1
	}
	first := calls[0].Timestamp
	last := calls[0].Timestamp
	for _, call := range calls {
		if call.Timestamp.Before(first) {
			first = call.Timestamp
		}
		if call.Timestamp.After(last) {
			last = call.Timestamp
		}
	}
	window := last.Sub(first)
	if window < 24*time.Hour {
		window = 24 * time.Hour
	}
	return (30 * 24 * time.Hour).Seconds() / window.Seconds()
}

func recommendRoute(calls []LLMCall, avgTokens float64) (string, float64, string) {
	if len(calls) >= 10 {
		return "semantic_cache -> smaller_model_fallback", 0.15, "Repeated high-confidence prompt pattern. Cache common outputs and use a cheaper fallback."
	}
	if avgTokens > 3500 {
		return "prompt_compression -> smaller_model_fallback", 0.45, "Large repeated context. Compress or extract deterministic fields before model escalation."
	}
	if strings.Contains(strings.ToLower(calls[0].Workflow), "classif") || strings.Contains(strings.ToLower(calls[0].Workflow), "triage") {
		return "local_classifier -> frontier_fallback", 0.25, "Classification-like workflow. Route confident cases locally and escalate uncertain cases."
	}
	return "rules_or_cache -> frontier_fallback", 0.35, "Repeated call pattern. Replace the common path with cache/rules and keep frontier fallback."
}

func splitRoute(route string) (string, string) {
	parts := strings.SplitN(route, "->", 2)
	if len(parts) == 1 {
		return strings.TrimSpace(route), "frontier_fallback"
	}
	return strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
}

func plural(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}
