package miser

import (
	"fmt"
	"strings"
)

type SavingsPlan struct {
	MonthlySpendAnalyzed    float64    `json:"monthly_spend_analyzed"`
	CostBasis               string     `json:"cost_basis,omitempty"`
	EstimatedAvoidableSpend float64    `json:"estimated_avoidable_spend"`
	SavingsOpportunity      float64    `json:"savings_opportunity"`
	Items                   []PlanItem `json:"items"`
}

type PlanItem struct {
	Workflow           string   `json:"workflow"`
	Finding            string   `json:"finding"`
	CurrentMonthlyCost float64  `json:"current_monthly_cost"`
	EstimatedSavings   float64  `json:"estimated_savings"`
	SavingsRate        float64  `json:"savings_rate"`
	RecommendedFixes   []string `json:"recommended_fixes"`
	QualityGuard       string   `json:"quality_guard"`
	Fallback           string   `json:"fallback"`
	Rollback           string   `json:"rollback"`
	Why                string   `json:"why"`
	CompetitorOverlap  []string `json:"competitor_overlap,omitempty"`
	MiserDifference    string   `json:"miser_difference"`
	SampleCallIDs      []string `json:"sample_call_ids"`
}

func Plan(calls []LLMCall) SavingsPlan {
	report := Audit(calls)
	items := make([]PlanItem, 0, len(report.TopWaste))
	for _, line := range report.TopWaste {
		items = append(items, planItem(line))
	}
	return SavingsPlan{
		MonthlySpendAnalyzed:    report.MonthlySpendAnalyzed,
		CostBasis:               report.CostBasis,
		EstimatedAvoidableSpend: report.EstimatedAvoidableSpend,
		SavingsOpportunity:      report.SavingsOpportunity,
		Items:                   items,
	}
}

func RenderPlanYAML(plan SavingsPlan) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by Miser. Review, replay-test, then deploy.")
	fmt.Fprintf(&b, "monthly_spend_analyzed: %.2f\n", plan.MonthlySpendAnalyzed)
	if plan.CostBasis != "" {
		fmt.Fprintf(&b, "cost_basis: %q\n", plan.CostBasis)
	}
	fmt.Fprintf(&b, "estimated_avoidable_spend: %.2f\n", plan.EstimatedAvoidableSpend)
	fmt.Fprintf(&b, "savings_opportunity: %.4f\n", plan.SavingsOpportunity)
	fmt.Fprintln(&b, "items:")
	if len(plan.Items) == 0 {
		fmt.Fprintln(&b, "  []")
		return b.String()
	}
	for _, item := range plan.Items {
		fmt.Fprintf(&b, "  - workflow: %s\n", yamlScalar(item.Workflow))
		fmt.Fprintf(&b, "    finding: %s\n", yamlScalar(item.Finding))
		fmt.Fprintf(&b, "    current_monthly_cost: %.2f\n", item.CurrentMonthlyCost)
		fmt.Fprintf(&b, "    estimated_savings: %.2f\n", item.EstimatedSavings)
		fmt.Fprintf(&b, "    savings_rate: %.4f\n", item.SavingsRate)
		fmt.Fprintln(&b, "    recommended_fixes:")
		for _, fix := range item.RecommendedFixes {
			fmt.Fprintf(&b, "      - %s\n", yamlScalar(fix))
		}
		fmt.Fprintf(&b, "    quality_guard: %s\n", yamlScalar(item.QualityGuard))
		fmt.Fprintf(&b, "    fallback: %s\n", yamlScalar(item.Fallback))
		fmt.Fprintf(&b, "    rollback: %s\n", yamlScalar(item.Rollback))
		fmt.Fprintf(&b, "    why: %s\n", yamlScalar(item.Why))
		if len(item.CompetitorOverlap) > 0 {
			fmt.Fprintln(&b, "    competitor_overlap:")
			for _, overlap := range item.CompetitorOverlap {
				fmt.Fprintf(&b, "      - %s\n", yamlScalar(overlap))
			}
		}
		fmt.Fprintf(&b, "    miser_difference: %s\n", yamlScalar(item.MiserDifference))
		if len(item.SampleCallIDs) > 0 {
			fmt.Fprintln(&b, "    sample_call_ids:")
			for _, id := range item.SampleCallIDs {
				fmt.Fprintf(&b, "      - %s\n", yamlScalar(id))
			}
		}
	}
	return b.String()
}

func RenderPlan(plan SavingsPlan) string {
	if len(plan.Items) == 0 {
		return "Miser found no executable savings plans.\n"
	}
	var b strings.Builder
	fmt.Fprintln(&b, "Miser Savings Plan")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "Monthly spend analyzed: %s\n", dollars(plan.MonthlySpendAnalyzed))
	if plan.CostBasis != "" {
		fmt.Fprintf(&b, "Cost basis: %s\n", plan.CostBasis)
	}
	fmt.Fprintf(&b, "Estimated avoidable spend: %s\n", dollars(plan.EstimatedAvoidableSpend))
	fmt.Fprintf(&b, "Savings opportunity: %.1f%%\n", plan.SavingsOpportunity*100)
	for i, item := range plan.Items {
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "%d. %s\n", i+1, item.Workflow)
		fmt.Fprintf(&b, "Finding: %s\n", item.Finding)
		fmt.Fprintf(&b, "Estimated savings: %s (%.0f%%)\n", dollars(item.EstimatedSavings), item.SavingsRate*100)
		fmt.Fprintf(&b, "Recommended fixes: %s\n", strings.Join(item.RecommendedFixes, ", "))
		fmt.Fprintf(&b, "Quality guard: %s\n", item.QualityGuard)
		fmt.Fprintf(&b, "Fallback: %s\n", item.Fallback)
		fmt.Fprintf(&b, "Why: %s\n", item.Why)
	}
	return b.String()
}

func planItem(line WasteLine) PlanItem {
	fixes, fallback, overlap := planFixes(line.Label)
	currentMonthlyCost := line.EstimatedMonthlyWaste
	if line.WorkflowSavingsRate > 0 {
		currentMonthlyCost = line.EstimatedMonthlyWaste / line.WorkflowSavingsRate
	}
	return PlanItem{
		Workflow:           workflowSlug(line.Label),
		Finding:            line.Label,
		CurrentMonthlyCost: currentMonthlyCost,
		EstimatedSavings:   line.EstimatedMonthlyWaste,
		SavingsRate:        line.WorkflowSavingsRate,
		RecommendedFixes:   fixes,
		QualityGuard:       "replay_eval >= 0.95",
		Fallback:           fallback,
		Rollback:           "keep current route behind a feature flag",
		Why:                line.Reason,
		CompetitorOverlap:  overlap,
		MiserDifference:    "bill-backed savings receipt plus executable policy",
		SampleCallIDs:      line.SampleCallIDs,
	}
}

func planFixes(label string) ([]string, string, []string) {
	switch label {
	case "Coding-agent context replay":
		return []string{"bounded_context", "repo_handoff", "folded_tool_outputs", "prefix_cache_discipline"}, "current_model", []string{"inferoa", "headroom", "codemap"}
	case "Coding-agent context reconstruction":
		return []string{"repo_map", "session_handoff", "working_set_tracking", "bounded_context"}, "current_model", []string{"codemap", "inferoa"}
	case "High-volume provider API usage":
		return []string{"per_project_drilldown", "model_routing", "semantic_cache", "usage_budget"}, "current_model", []string{"inferoa"}
	case "Repeated long-context calls":
		return []string{"context_compression", "content_type_aware_trimming", "semantic_cache", "smaller_model_fallback"}, "frontier_model", []string{"headroom"}
	case "Expensive model used for classification":
		return []string{"local_classifier", "rules_first", "confidence_threshold", "frontier_fallback"}, "frontier_model", nil
	case "Duplicate summaries":
		return []string{"exact_cache", "semantic_cache", "template_response", "smaller_model_fallback"}, "frontier_model", []string{"headroom"}
	case "Agent retry loops":
		return []string{"tool_result_cache", "retry_budget", "deterministic_failure_handling", "loop_guardrails"}, "current_model", []string{"inferoa"}
	case "Oversized PDF prompts":
		return []string{"document_chunking", "deterministic_extraction", "template_first", "frontier_review_only"}, "frontier_model", []string{"headroom"}
	default:
		return []string{"semantic_cache", "model_routing", "quality_guard", "fallback_route"}, "current_model", nil
	}
}

func workflowSlug(value string) string {
	value = strings.ToLower(value)
	var b strings.Builder
	lastDash := false
	for _, r := range value {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			b.WriteByte('_')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "_")
}

func yamlScalar(value string) string {
	escaped := strings.ReplaceAll(value, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
	return "\"" + escaped + "\""
}
