package miser

import (
	"fmt"
	"strings"
)

type AgentRulePack struct {
	Version                 string      `json:"version"`
	Target                  string      `json:"target"`
	MonthlySpendAnalyzed    float64     `json:"monthly_spend_analyzed"`
	CostBasis               string      `json:"cost_basis,omitempty"`
	EstimatedAvoidableSpend float64     `json:"estimated_avoidable_spend"`
	SavingsOpportunity      float64     `json:"savings_opportunity"`
	Rules                   []AgentRule `json:"rules"`
}

type AgentRule struct {
	ID                     string            `json:"id"`
	Workflow               string            `json:"workflow"`
	Finding                string            `json:"finding"`
	Trigger                string            `json:"trigger"`
	ExpectedMonthlySavings float64           `json:"expected_monthly_savings"`
	SavingsRate            float64           `json:"savings_rate"`
	Limits                 map[string]string `json:"limits"`
	Enforcement            []string          `json:"enforcement"`
	QualityGuard           string            `json:"quality_guard"`
	Fallback               string            `json:"fallback"`
	Rollback               string            `json:"rollback"`
	Metrics                []string          `json:"metrics"`
	Evidence               []string          `json:"evidence"`
}

func Rules(calls []LLMCall, target string) AgentRulePack {
	if target == "" {
		target = "generic"
	}
	plan := Plan(calls)
	rules := make([]AgentRule, 0, len(plan.Items))
	for _, item := range plan.Items {
		rules = append(rules, ruleForPlanItem(item, target))
	}
	return AgentRulePack{
		Version:                 "miser.rules/v1",
		Target:                  target,
		MonthlySpendAnalyzed:    plan.MonthlySpendAnalyzed,
		CostBasis:               plan.CostBasis,
		EstimatedAvoidableSpend: plan.EstimatedAvoidableSpend,
		SavingsOpportunity:      plan.SavingsOpportunity,
		Rules:                   rules,
	}
}

func RenderRulesYAML(pack AgentRulePack) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by Miser. Treat this as policy-as-code: review, replay-test, then enforce.")
	fmt.Fprintf(&b, "version: %s\n", yamlScalar(pack.Version))
	fmt.Fprintf(&b, "target: %s\n", yamlScalar(pack.Target))
	fmt.Fprintf(&b, "monthly_spend_analyzed: %.2f\n", pack.MonthlySpendAnalyzed)
	if pack.CostBasis != "" {
		fmt.Fprintf(&b, "cost_basis: %s\n", yamlScalar(pack.CostBasis))
	}
	fmt.Fprintf(&b, "estimated_avoidable_spend: %.2f\n", pack.EstimatedAvoidableSpend)
	fmt.Fprintf(&b, "savings_opportunity: %.4f\n", pack.SavingsOpportunity)
	fmt.Fprintln(&b, "rules:")
	if len(pack.Rules) == 0 {
		fmt.Fprintln(&b, "  []")
		return b.String()
	}
	for _, rule := range pack.Rules {
		fmt.Fprintf(&b, "  - id: %s\n", yamlScalar(rule.ID))
		fmt.Fprintf(&b, "    workflow: %s\n", yamlScalar(rule.Workflow))
		fmt.Fprintf(&b, "    finding: %s\n", yamlScalar(rule.Finding))
		fmt.Fprintf(&b, "    trigger: %s\n", yamlScalar(rule.Trigger))
		fmt.Fprintf(&b, "    expected_monthly_savings: %.2f\n", rule.ExpectedMonthlySavings)
		fmt.Fprintf(&b, "    savings_rate: %.4f\n", rule.SavingsRate)
		fmt.Fprintln(&b, "    limits:")
		for _, key := range sortedRuleLimitKeys(rule.Limits) {
			fmt.Fprintf(&b, "      %s: %s\n", key, yamlScalar(rule.Limits[key]))
		}
		fmt.Fprintln(&b, "    enforcement:")
		for _, step := range rule.Enforcement {
			fmt.Fprintf(&b, "      - %s\n", yamlScalar(step))
		}
		fmt.Fprintf(&b, "    quality_guard: %s\n", yamlScalar(rule.QualityGuard))
		fmt.Fprintf(&b, "    fallback: %s\n", yamlScalar(rule.Fallback))
		fmt.Fprintf(&b, "    rollback: %s\n", yamlScalar(rule.Rollback))
		fmt.Fprintln(&b, "    metrics:")
		for _, metric := range rule.Metrics {
			fmt.Fprintf(&b, "      - %s\n", yamlScalar(metric))
		}
		if len(rule.Evidence) > 0 {
			fmt.Fprintln(&b, "    evidence:")
			for _, evidence := range rule.Evidence {
				fmt.Fprintf(&b, "      - %s\n", yamlScalar(evidence))
			}
		}
	}
	return b.String()
}

func RenderAgentInstructions(pack AgentRulePack) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# Miser Agent Rules")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "Target: `%s`\n", pack.Target)
	fmt.Fprintf(&b, "Spend analyzed: %s\n", dollars(pack.MonthlySpendAnalyzed))
	if pack.CostBasis != "" {
		fmt.Fprintf(&b, "Cost basis: %s\n", pack.CostBasis)
	}
	fmt.Fprintf(&b, "Estimated avoidable spend: %s\n", dollars(pack.EstimatedAvoidableSpend))
	fmt.Fprintln(&b)
	if len(pack.Rules) == 0 {
		fmt.Fprintln(&b, "Miser did not find a rule worth enforcing yet.")
		return b.String()
	}
	for _, rule := range pack.Rules {
		fmt.Fprintf(&b, "## %s\n", rule.ID)
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "Finding: %s\n", rule.Finding)
		fmt.Fprintf(&b, "Expected savings: %s (%.0f%%)\n", dollars(rule.ExpectedMonthlySavings), rule.SavingsRate*100)
		fmt.Fprintf(&b, "Trigger: %s\n", rule.Trigger)
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "Do this:")
		for _, step := range rule.Enforcement {
			fmt.Fprintf(&b, "- %s\n", step)
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "Limits:")
		for _, key := range sortedRuleLimitKeys(rule.Limits) {
			fmt.Fprintf(&b, "- `%s`: %s\n", key, rule.Limits[key])
		}
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "Quality guard: `%s`\n", rule.QualityGuard)
		fmt.Fprintf(&b, "Fallback: `%s`\n", rule.Fallback)
		fmt.Fprintf(&b, "Rollback: %s\n", rule.Rollback)
		fmt.Fprintln(&b)
	}
	return b.String()
}

func ruleForPlanItem(item PlanItem, target string) AgentRule {
	switch item.Workflow {
	case "coding_agent_context_replay":
		return AgentRule{
			ID:                     "miser.coding_agent_context_replay.v1",
			Workflow:               item.Workflow,
			Finding:                item.Finding,
			Trigger:                "cached_input_tokens/input_tokens >= 0.50 and output_tokens/(input_tokens+output_tokens) <= 0.10",
			ExpectedMonthlySavings: item.EstimatedSavings,
			SavingsRate:            item.SavingsRate,
			Limits: map[string]string{
				"max_context_files":          "12",
				"max_replayed_prompt_tokens": "8000",
				"max_tool_output_lines":      "200",
				"session_handoff_after":      "20m or before switching tasks",
			},
			Enforcement:  contextReplayEnforcement(target),
			QualityGuard: item.QualityGuard,
			Fallback:     item.Fallback,
			Rollback:     item.Rollback,
			Metrics: []string{
				"input_tokens",
				"cached_input_tokens",
				"output_tokens",
				"context_files_count",
				"tool_output_lines",
				"replay_eval_score",
				"actual_invoice_allocated_cost_usd",
			},
			Evidence: item.SampleCallIDs,
		}
	default:
		return AgentRule{
			ID:                     "miser." + item.Workflow + ".v1",
			Workflow:               item.Workflow,
			Finding:                item.Finding,
			Trigger:                "finding appears in Miser audit",
			ExpectedMonthlySavings: item.EstimatedSavings,
			SavingsRate:            item.SavingsRate,
			Limits: map[string]string{
				"quality_guard":      item.QualityGuard,
				"feature_flag":       "required",
				"fallback_route":     item.Fallback,
				"rollback_available": "true",
			},
			Enforcement:  genericEnforcement(item),
			QualityGuard: item.QualityGuard,
			Fallback:     item.Fallback,
			Rollback:     item.Rollback,
			Metrics: []string{
				"current_monthly_cost",
				"optimized_monthly_cost",
				"replay_eval_score",
				"fallback_rate",
				"actual_invoice_allocated_cost_usd",
			},
			Evidence: item.SampleCallIDs,
		}
	}
}

func contextReplayEnforcement(target string) []string {
	steps := []string{
		"Start each task from a short repo/session summary before reopening files.",
		"Only include files directly needed for the active task; prefer file paths and line references over pasted file bodies.",
		"Fold command output over 200 lines into a short summary plus the exact command and file references.",
		"Keep stable system/developer/tool instructions unchanged to preserve provider prefix-cache hits.",
		"Write a handoff summary before switching tasks or after 20 minutes of work.",
		"Escalate to the current model when the replay eval drops below 0.95 or the agent cannot locate needed context.",
	}
	switch target {
	case "codex":
		return append([]string{"For Codex, store the handoff in the thread/worktree notes and prefer `rg`/file references before re-reading broad context."}, steps...)
	case "claude":
		return append([]string{"For Claude Code, keep CLAUDE.md concise and move long command/file outputs into referenced artifacts instead of chat context."}, steps...)
	default:
		return steps
	}
}

func genericEnforcement(item PlanItem) []string {
	steps := make([]string, 0, len(item.RecommendedFixes)+3)
	for _, fix := range item.RecommendedFixes {
		steps = append(steps, "Implement "+strings.ReplaceAll(fix, "_", " ")+".")
	}
	steps = append(steps,
		"Replay-test against sampled calls before enforcing.",
		"Ship behind a feature flag with the current route as fallback.",
		"Track realized savings against actual invoice allocated cost.",
	)
	return steps
}

func sortedRuleLimitKeys(values map[string]string) []string {
	preferred := []string{
		"max_context_files",
		"max_replayed_prompt_tokens",
		"max_tool_output_lines",
		"session_handoff_after",
		"quality_guard",
		"feature_flag",
		"fallback_route",
		"rollback_available",
	}
	var keys []string
	seen := map[string]bool{}
	for _, key := range preferred {
		if _, ok := values[key]; ok {
			keys = append(keys, key)
			seen[key] = true
		}
	}
	for key := range values {
		if !seen[key] {
			keys = append(keys, key)
		}
	}
	return keys
}
